redis:
  enable: false  #默认不开启redis作为远程缓存，默认采用go-cache进程内缓存
  address:
  port:
  password:

mysql:
  address: localhost
  port: 3306
  database: neubot
  user: neubot
  password:

cqhttp:
  address: 0.0.0.0
  port: 5700

bot:
  port: 8085 #启动端口
  idleThreadNum: 20 #线程池容量
  master: 1150840779 #管理员QQ账号，支持群发以及接受反馈消息,目前尚未实现群发

cloud:
  appId: xxxxx  #调用腾讯云chat接口的id
  appSecret: xxxxx  #调用腾讯云chat接口的密钥
  enable: false   #是否调用聊天api
