redis:
  enable: false  #默认不开启redis作为远程缓存，默认采用go-cache进程内缓存
  address:
  port:
  password:

mysql:
  address: localhost
  port: 3306
  database: neubot
  user: root
  password: xgs583719992

cqhttp:
  address: 0.0.0.0
  port: 3050

bot:
  port: 3005 #启动端口
  idleThreadNum: 20 #线程池容量
  master: 1150840779 #管理员QQ账号，支持群发以及接受反馈消息,目前尚未实现群发

chat:
  appId: xxxxxxxxxxxxxxxxx  #调用腾讯云chat接口的id
  appSecret: xxxxxxxxxxxxxxxxxx  #调用腾讯云chat接口的密钥
  enable: true   #是否调用聊天api
